curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
abline(v=1.5, lty="dashed", col="blue")
text(1.7,0.2,expression(X * beta))
abline(v=0, lty="dashed", col="red")

x <- c(-4,seq(-4,0,by=0.01),0,-4)
y <- c(0,dnorm(seq(-4,0,by=0.01),mean=1.5),0,0)
polygon(x,y,col="grey")
text(-0.3, 0.03, round(pnorm(-1.5),3))

pdf("img/fig02a.pdf", height=5, width=8)
curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
dev.off()

pdf("img/fig02b.pdf", height=5, width=8)
curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
abline(v=1.5, lty="dashed", col="blue")
text(1.7,0.2,expression(X * beta))
dev.off()

pdf("img/fig02c.pdf", height=5, width=8)
curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
abline(v=1.5, lty="dashed", col="blue")
abline(v=0, lty="dashed", col="red")
text(1.7,0.2,expression(X * beta))
dev.off()

pdf("img/fig02d.pdf", height=5, width=8)
curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
abline(v=1.5, lty="dashed", col="blue")
text(1.7,0.2,expression(X * beta))
abline(v=0, lty="dashed", col="red")
x <- c(-4,seq(-4,0,by=0.01),0,-4)
y <- c(0,dnorm(seq(-4,0,by=0.01),mean=1.5),0,0)
polygon(x,y,col="grey")
dev.off()

pdf("img/fig02e.pdf", height=5, width=8)
curve(dnorm(x,mean=1.5), -4, 4, xlab="z", ylab="denstiy")
abline(v=1.5, lty="dashed", col="blue")
text(1.7,0.2,expression(X * beta))
abline(v=0, lty="dashed", col="red")
x <- c(-4,seq(-4,0,by=0.01),0,-4)
y <- c(0,dnorm(seq(-4,0,by=0.01),mean=1.5),0,0)
polygon(x,y,col="grey")
text(-0.3, 0.03, round(pnorm(-1.5),3))
dev.off()


